services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pet_family
    ports:
      - "5430:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: